name: Initialize input variables

on:
  workflow_call:
    outputs:
      BRANCH:
        description: "branch name"
        value: ${{ jobs.init-inputs.outputs.BRANCH }}

      ENVIRONMENT:
        description: "environment name"
        value: ${{ jobs.init-inputs.outputs.ENVIRONMENT }}

      ARTIFACT_VERSION:
        description: "environment name"
        value: ${{ jobs.init-inputs.outputs.ARTIFACT_VERSION }}
          
 
jobs:
  init-inputs:
    runs-on: ubuntu-latest
    outputs:   
      BRANCH: ${{steps.initVars.outputs.BRANCH}}
      ENVIRONMENT: ${{steps.initVars.outputs.ENVIRONMENT}}
      ARTIFACT_VERSION:  ${{steps.initVars.outputs.ARTIFACT_VERSION}}
      
    steps:
    - name: Initialize Inputs
      id: initVars
      run: |  
        echo ${{ github.ref }}
        echo ${{ github.ref_name }}
        echo ${{ github.event_name }}
        
        if [[ "${{ github.ref_name }}" == *"develop" ]]; then
          echo "BRANCH=develop" >> "$GITHUB_OUTPUT"
          echo "ENVIRONMENT=dev" >> "$GITHUB_OUTPUT"
      
        elif [[ "${{ github.ref_name }}" == *"main" ]]; then
          echo "BRANCH=main" >> "$GITHUB_OUTPUT"
          echo "ENVIRONMENT=prod"  >> "$GITHUB_OUTPUT"      
        fi
        
        project_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "project Version = '$project_version'"
        IFS='-'
        read -ra arr <<< "$project_version"
        art_version=${arr[0]}
        echo "version=$art_version"
        echo "ARTIFACT_VERSION=$art_version"  >> "$GITHUB_OUTPUT"

    - name: Print the outputs
      run: |
        echo "BRANCH: ${{steps.initVars.outputs.BRANCH}}"
        echo "ENVIRONMENT: ${{steps.initVars.outputs.ENVIRONMENT}}"
        echo "ARTIFACT_VERSION: ${{steps.initVars.outputs.ARTIFACT_VERSION}}"